apiVersion: v1
kind: Service
metadata:
  name: academia-app
spec:
  selector:
    app: academia-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: academia-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: academia-app
  template:
    metadata:
      labels:
        app: academia-app
    spec:
      containers:
      - name: academia-app
        image: mnjoao/academia:V1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-db:3306/academiaDB
        - name: HABILITAR_CARREGAR_MASSA_DADOS
          value: "false"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
