version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: academia-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha01
      MYSQL_DATABASE: academiaDB
    ports:
      - "3307:3307"
    cap_add:
      - SYS_NICE
    networks:
      - academia

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus 
    ports:
      - "9090:9090"
    networks:
      - academia

  app:
    image: mnjoao/academia:V2
    container_name: academia_app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/academiaDB
      HABILITAR_CARREGAR_MASSA_DADOS: 'false'
    ports:
      - "8080:8080"  # host:container
    networks:
      - academia

networks:
  academia:
    driver: bridge
