version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: academia-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha01
      MYSQL_DATABASE: academiaDB
    ports:
    - "3306:3306"
    cap_add:
      - SYS_NICE
  app:
    image: mnjoao/academia:V1
    container_name: academia_app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/academiaDB
      HABILITAR_CARREGAR_MASSA_DADOS: 'false'
    ports:
     - "9090:8080"  # host:container
